
import type { User, Employee, Role, EmployeeCertificate } from './types';

export const ROLES: Record<string, Role> = {
  HRO: "HRO",
  HHRMD: "HHRMD",
  HRMO: "HRMO",
  DO: "DO",
  EMPLOYEE: "EMPLOYEE",
  CSCS: "CSCS", // Civil Service Commission Secretary
  HRRP: "HRRP", // Human Resource Responsible Personnel
  PO: "PO", // Planning Officer
};

export const USERS: User[] = [
  { id: "user_cscs", username: "zhaji", name: "Zaituni Haji", role: ROLES.CSCS as Role },
  { id: "user2", username: "skhamis", name: "Safia Khamis", role: ROLES.HHRMD as Role },
  { id: "user_hrmo", username: "fiddi", name: "Fauzia Iddi", role: ROLES.HRMO as Role },
  { id: "user_hrrp", username: "khamadi", name: "Khamis Hamadi", role: ROLES.HRRP as Role, institutionId: "inst_pc", institution: "TUME YA MIPANGO" },
  { id: "user_po", username: "mishak", name: "Mwanakombo Is-hak", role: ROLES.PO as Role },
  { id: "user_hro_cgo", username: "kmnyonge", name: "Khamis Mnyonge", role: ROLES.HRO as Role, institutionId: "inst_cgo", institution: "AFISI YA RAIS FEDHA NA MIPANGO" },
  { id: "user_hro_moe", username: "ahmedm", name: "Ahmed Mohammed", role: ROLES.HRO as Role, institutionId: "inst_moe", institution: "WIZARA YA ELIMU NA MAFUNZO YA AMALI" },
  { id: "user5", username: "mussi", name: "Maimuna Ussi", role: ROLES.DO as Role },
  { id: "emp1_user", username: "alijuma", name: "Ali Juma Ali", role: ROLES.EMPLOYEE as Role, employeeId: "emp1" },
  { id: "emp8_user", username: "khadijanassor", name: "Khadija Nassor", role: ROLES.EMPLOYEE as Role, employeeId: "emp8" },
  { id: "emp9_user", username: "yussufmakame", name: "Yussuf Makame", role: ROLES.EMPLOYEE as Role, employeeId: "emp9" },
];

export const EMPLOYEES: Employee[] = [
  { 
    id: "emp1", 
    employeeEntityId: "emp1_id", 
    name: "Ali Juma Ali", 
    gender: 'Male',
    zanId: "221458232", 
    zssfNumber: "ZSSF001",
    payrollNumber: "PAY001",
    phoneNumber: "0777-123-456",
    contactAddress: "P.O. Box 123, Migombani, Zanzibar",
    dateOfBirth: "1980-05-15",
    placeOfBirth: "Zanzibar City",
    region: "Mjini Magharibi",
    countryOfBirth: "Tanzania",
    status: "On Probation", 
    cadre: "Administrative Officer",
    salaryScale: "ZPS 4.2", 
    department: "Administration",
    ministry: "Public Service and Good Governance",
    institutionId: "inst_cgo",
    institution: "Central Government Office",
    appointmentType: "Permanent",
    contractType: "Full-time",
    recentTitleDate: "2023-01-10",
    currentReportingOffice: "Director of Administration",
    currentWorkplace: "HQ Office",
    employmentDate: "2023-01-10",
    confirmationDate: undefined, 
    retirementDate: "2040-05-15",
    ardhilHaliUrl: "https://placehold.co/ardhil-hali.pdf",
    confirmationLetterUrl: undefined,
    jobContractUrl: "https://placehold.co/job-contract-ali.pdf",
    birthCertificateUrl: "https://placehold.co/birth-cert-ali.pdf",
    profileImageUrl: "https://placehold.co/100x100.png?text=AJA",
    certificates: [
      { type: "Bachelor Degree", name: "B.A. Public Administration", url: "https://placehold.co/bachelor-ali.pdf" },
      { type: "Certificate", name: "Certificate in Office Management", url: "https://placehold.co/cert-ali.pdf" },
    ],
  },
  { 
    id: "emp2", 
    employeeEntityId: "emp2_id", 
    name: "Safia Juma Ali", 
    gender: 'Female',
    zanId: "125468957", 
    zssfNumber: "ZSSF002",
    payrollNumber: "PAY002",
    phoneNumber: "0777-234-567",
    contactAddress: "P.O. Box 456, Wete, Pemba",
    dateOfBirth: "1990-11-22",
    placeOfBirth: "Wete, Pemba",
    region: "Kaskazini Pemba",
    countryOfBirth: "Tanzania",
    status: "Confirmed", 
    cadre: "HR Officer", 
    salaryScale: "ZPS 6.1",
    department: "Human Resources",
    ministry: "Public Service and Good Governance",
    institutionId: "inst_csc",
    institution: "Civil Service Commission",
    appointmentType: "Permanent",
    contractType: "Full-time",
    recentTitleDate: "2021-06-01",
    currentReportingOffice: "Head of HR",
    currentWorkplace: "CSC Building",
    employmentDate: "2020-12-01",
    confirmationDate: "2021-06-01",
    retirementDate: "2050-11-22",
    ardhilHaliUrl: "https://placehold.co/ardhil-hali-safia.pdf",
    confirmationLetterUrl: "https://placehold.co/confirmation-safia.pdf",
    jobContractUrl: "https://placehold.co/job-contract-safia.pdf",
    birthCertificateUrl: undefined,
    profileImageUrl: "https://placehold.co/100x100.png?text=SJA",
    certificates: [
      { type: "Master Degree", name: "MSc Human Resource Management", url: "https://placehold.co/masters-safia.pdf" },
      { type: "Bachelor Degree", name: "BSc Business Administration", url: "https://placehold.co/bachelor-safia.pdf" },
    ],
  },
  { 
    id: "emp3", 
    employeeEntityId: "emp3_id", 
    name: "Fatma Said Omar", 
    gender: 'Female',
    zanId: "334589123", 
    zssfNumber: "ZSSF003",
    payrollNumber: "PAY003",
    phoneNumber: "0777-345-678",
    contactAddress: "P.O. Box 789, Chake Chake, Pemba",
    dateOfBirth: "1988-02-10",
    placeOfBirth: "Chake Chake, Pemba",
    region: "Kusini Pemba",
    countryOfBirth: "Tanzania",
    status: "On LWOP", 
    cadre: "Accountant", 
    salaryScale: "ZPS 5.3",
    department: "Finance",
    ministry: "Finance and Planning",
    institutionId: "inst_to",
    institution: "Treasury Office",
    appointmentType: "Permanent",
    contractType: "Full-time",
    recentTitleDate: "2019-03-15",
    currentReportingOffice: "Chief Accountant",
    currentWorkplace: "Treasury Building",
    employmentDate: "2018-09-15",
    confirmationDate: "2019-03-15",
    retirementDate: "2048-02-10",
    ardhilHaliUrl: "https://placehold.co/ardhil-hali-fatma.pdf",
    confirmationLetterUrl: "https://placehold.co/confirmation-fatma.pdf",
    jobContractUrl: undefined,
    birthCertificateUrl: "https://placehold.co/birth-cert-fatma.pdf",
    certificates: [
      { type: "Diploma", name: "Diploma in Accountancy", url: "https://placehold.co/diploma-fatma.pdf" },
    ],
  },
  { 
    id: "emp4", 
    employeeEntityId: "emp4_id", 
    name: "Hassan Mzee Juma", 
    gender: 'Male',
    zanId: "445678912", 
    zssfNumber: "ZSSF004",
    payrollNumber: "PAY004",
    phoneNumber: "0777-456-789",
    contactAddress: "P.O. Box 101, Unguja Ukuu",
    dateOfBirth: "1975-09-01",
    placeOfBirth: "Unguja Ukuu",
    region: "Kusini Unguja",
    countryOfBirth: "Tanzania",
    status: "Confirmed", 
    cadre: "IT Support",
    salaryScale: "ZPS 4.1", 
    department: "ICT",
    ministry: "Information, Communication and Information Technology",
    institutionId: "inst_ega",
    institution: "e-Government Agency",
    appointmentType: "Permanent",
    contractType: "Full-time",
    recentTitleDate: "2017-07-20",
    currentReportingOffice: "Head of ICT",
    currentWorkplace: "Tech Park",
    employmentDate: "2011-11-11", // Hired before May 2014
    confirmationDate: "2012-05-11",
    retirementDate: "2035-09-01",
    jobContractUrl: "https://placehold.co/job-contract-hassan.pdf",
    birthCertificateUrl: "https://placehold.co/birth-cert-hassan.pdf",
    certificates: [], 
  },
  { 
    id: "emp5", 
    employeeEntityId: "emp5_id", 
    name: "Zainab Ali Khamis", 
    gender: 'Female',
    zanId: "556789345", 
    zssfNumber: "ZSSF005",
    payrollNumber: "PAY005",
    phoneNumber: "0777-567-890",
    contactAddress: "P.O. Box 212, Mkoani, Pemba",
    dateOfBirth: "1992-12-30",
    placeOfBirth: "Mkoani, Pemba",
    region: "Kusini Pemba",
    countryOfBirth: "Tanzania",
    status: "Confirmed", 
    cadre: "Planning Officer",
    salaryScale: "ZPS 5.2", 
    department: "Planning",
    ministry: "Finance and Planning",
    institutionId: "inst_pc",
    institution: "Planning Commission",
    appointmentType: "Permanent",
    contractType: "Full-time",
    recentTitleDate: "2022-08-01",
    currentReportingOffice: "Director of Planning",
    currentWorkplace: "Planning HQ",
    employmentDate: "2022-02-01",
    confirmationDate: "2022-08-01",
    retirementDate: "2052-12-30",
    jobContractUrl: undefined,
    birthCertificateUrl: undefined,
  },
  { 
    id: "emp6", 
    employeeEntityId: "emp6_id", 
    name: "Juma Omar Ali", 
    gender: 'Male',
    zanId: "667890456", 
    zssfNumber: "ZSSF006",
    payrollNumber: "PAY006",
    phoneNumber: "0777-678-901",
    contactAddress: "P.O. Box 313, Stone Town, Zanzibar",
    dateOfBirth: "1983-06-18",
    placeOfBirth: "Zanzibar City",
    region: "Mjini Magharibi",
    countryOfBirth: "Tanzania",
    status: "Confirmed", 
    cadre: "Procurement Officer",
    salaryScale: "ZPS 5.1", 
    department: "Procurement",
    ministry: "Finance and Planning",
    institutionId: "inst_gpsa",
    institution: "Government Procurement Services Agency",
    appointmentType: "Permanent",
    contractType: "Full-time",
    recentTitleDate: "2016-04-11",
    currentReportingOffice: "Head of Procurement",
    currentWorkplace: "GPSA Office",
    employmentDate: "2015-10-11",
    confirmationDate: "2016-04-11",
    retirementDate: "2043-06-18",
    jobContractUrl: "https://placehold.co/job-contract-juma.pdf",
    birthCertificateUrl: "https://placehold.co/birth-cert-juma.pdf",
  },
  { 
    id: "emp7", 
    employeeEntityId: "emp7_id", 
    name: "Hamid Khalfan Abdalla", 
    gender: 'Male',
    zanId: "778901234", 
    zssfNumber: "ZSSF007",
    payrollNumber: "PAY007",
    phoneNumber: "0777-789-012",
    contactAddress: "P.O. Box 414, Forodhani, Zanzibar",
    dateOfBirth: "1978-03-25",
    placeOfBirth: "Stone Town",
    region: "Mjini Magharibi",
    countryOfBirth: "Tanzania",
    status: "Confirmed", 
    cadre: "Senior Driver", 
    salaryScale: "ZPS 3.3",
    department: "Transport",
    ministry: "Works and Transport",
    institutionId: "inst_gg",
    institution: "Government Garage",
    appointmentType: "Permanent",
    contractType: "Full-time",
    recentTitleDate: "2015-01-01",
    currentReportingOffice: "Transport Officer",
    currentWorkplace: "Central Garage",
    employmentDate: "2010-01-01",
    confirmationDate: "2010-07-01",
    retirementDate: "2038-03-25",
    ardhilHaliUrl: "https://placehold.co/ardhil-hali-hamid.pdf",
    confirmationLetterUrl: "https://placehold.co/confirmation-hamid.pdf",
    jobContractUrl: "https://placehold.co/job-contract-hamid.pdf",
    birthCertificateUrl: "https://placehold.co/birth-cert-hamid.pdf",
  },
  { 
    id: "emp8", 
    employeeEntityId: "emp8_id", 
    name: "Khadija Nassor", 
    gender: 'Female',
    zanId: "890123456", 
    zssfNumber: "ZSSF008",
    payrollNumber: "PAY008",
    phoneNumber: "0777-890-123",
    contactAddress: "P.O. Box 515, Michenzani, Zanzibar",
    dateOfBirth: "1970-01-20",
    placeOfBirth: "Zanzibar City",
    region: "Mjini Magharibi",
    countryOfBirth: "Tanzania",
    status: "Confirmed", 
    cadre: "Head Teacher",
    salaryScale: "ZPS 7.1", 
    department: "Secondary Education",
    ministry: "Education and Vocational Training",
    institutionId: "inst_moe",
    institution: "Ministry of Education",
    appointmentType: "Permanent",
    contractType: "Full-time",
    recentTitleDate: "2005-06-10",
    currentReportingOffice: "District Education Officer",
    currentWorkplace: "Ben Bella Secondary School",
    employmentDate: "1990-07-15", // Hired before May 2014
    confirmationDate: "1991-01-15",
    retirementDate: "2030-01-20",
  },
  { 
    id: "emp9", 
    employeeEntityId: "emp9_id", 
    name: "Yussuf Makame", 
    gender: 'Male',
    zanId: "901234567", 
    zssfNumber: "ZSSF009",
    payrollNumber: "PAY009",
    phoneNumber: "0777-901-234",
    contactAddress: "P.O. Box 616, Wawi, Pemba",
    dateOfBirth: "1995-04-11",
    placeOfBirth: "Wawi",
    region: "Kusini Pemba",
    countryOfBirth: "Tanzania",
    status: "On Probation", 
    cadre: "Teacher",
    salaryScale: "ZPS 4.1", 
    department: "Primary Education",
    ministry: "Education and Vocational Training",
    institutionId: "inst_moe",
    institution: "Ministry of Education",
    appointmentType: "Permanent",
    contractType: "Full-time",
    recentTitleDate: "2018-08-20",
    currentReportingOffice: "Head Teacher",
    currentWorkplace: "Wawi Primary School",
    employmentDate: "2018-08-20", // Hired after May 2014
    confirmationDate: undefined,
    retirementDate: "2055-04-11",
  },
];

export const APP_NAME = "Civil Service Navigator";
