
import type { User, Employee, Role, EmployeeCertificate } from './types';

export const ROLES: Record<string, Role> = {
  HRO: "HRO",
  HHRMD: "HHRMD", // Renamed from HHRMD_HRMO
  HRMO: "HRMO",   // New role
  DO: "DO",
  EMPLOYEE: "EMPLOYEE",
};

export const USERS: User[] = [
  { id: "user2", username: "msmith", name: "M. Smith", role: ROLES.HHRMD as Role }, // Updated role
  { id: "user_hrmo", username: "jdoe", name: "J. Doe", role: ROLES.HRMO as Role }, // New HRMO user
  { id: "user3", username: "ajuma", name: "A. Juma", role: ROLES.HRO as Role },
  { id: "user5", username: "kabdul", name: "K. Abdul", role: ROLES.DO as Role },
  { id: "user7", username: "hmohamed", name: "Hamid Mohamed", role: ROLES.EMPLOYEE as Role, employeeId: "emp7" },
  { id: "emp1_user", username: "alijuma", name: "Ali Juma Ali", role: ROLES.EMPLOYEE as Role, employeeId: "emp1" },
  { id: "emp2_user", username: "safiajuma", name: "Safia Juma Ali", role: ROLES.EMPLOYEE as Role, employeeId: "emp2" },
  { id: "emp3_user", username: "fatmasaid", name: "Fatma Said Omar", role: ROLES.EMPLOYEE as Role, employeeId: "emp3" },
];

export const EMPLOYEES: Employee[] = [
  { 
    id: "emp1", 
    employeeEntityId: "emp1_id", 
    name: "Ali Juma Ali", 
    zanId: "221458232", 
    zssfNumber: "ZSSF001",
    payrollNumber: "PAY001",
    dateOfBirth: "1980-05-15",
    placeOfBirth: "Zanzibar City",
    region: "Mjini Magharibi",
    countryOfBirth: "Tanzania",
    status: "On Probation", 
    cadre: "Administrative Officer", 
    department: "Administration",
    ministry: "Public Service and Good Governance",
    institution: "Central Government Office",
    appointmentType: "Permanent",
    contractType: "Full-time",
    recentTitleDate: "2023-01-10",
    currentReportingOffice: "Director of Administration",
    currentWorkplace: "HQ Office",
    employmentDate: "2023-01-10",
    confirmationDate: undefined, // Not yet confirmed
    ardhilHaliUrl: "https://placehold.co/ardhil-hali.pdf",
    confirmationLetterUrl: undefined,
    profileImageUrl: "https://placehold.co/100x100.png?text=AJA",
    certificates: [
      { type: "Bachelor Degree", name: "B.A. Public Administration", url: "https://placehold.co/bachelor-ali.pdf" },
      { type: "Certificate", name: "Certificate in Office Management", url: "https://placehold.co/cert-ali.pdf" },
    ],
  },
  { 
    id: "emp2", 
    employeeEntityId: "emp2_id", 
    name: "Safia Juma Ali", 
    zanId: "125468957", 
    zssfNumber: "ZSSF002",
    payrollNumber: "PAY002",
    dateOfBirth: "1990-11-22",
    placeOfBirth: "Wete, Pemba",
    region: "Kaskazini Pemba",
    countryOfBirth: "Tanzania",
    status: "Confirmed", 
    cadre: "HR Officer", 
    department: "Human Resources",
    ministry: "Public Service and Good Governance",
    institution: "Civil Service Commission",
    appointmentType: "Permanent",
    contractType: "Full-time",
    recentTitleDate: "2021-06-01",
    currentReportingOffice: "Head of HR",
    currentWorkplace: "CSC Building",
    employmentDate: "2020-12-01",
    confirmationDate: "2021-06-01",
    ardhilHaliUrl: "https://placehold.co/ardhil-hali-safia.pdf",
    confirmationLetterUrl: "https://placehold.co/confirmation-safia.pdf",
    profileImageUrl: "https://placehold.co/100x100.png?text=SJA",
    certificates: [
      { type: "Master Degree", name: "MSc Human Resource Management", url: "https://placehold.co/masters-safia.pdf" },
      { type: "Bachelor Degree", name: "BSc Business Administration", url: "https://placehold.co/bachelor-safia.pdf" },
    ],
  },
  { 
    id: "emp3", 
    employeeEntityId: "emp3_id", 
    name: "Fatma Said Omar", 
    zanId: "334589123", 
    zssfNumber: "ZSSF003",
    payrollNumber: "PAY003",
    dateOfBirth: "1988-02-10",
    placeOfBirth: "Chake Chake, Pemba",
    region: "Kusini Pemba",
    countryOfBirth: "Tanzania",
    status: "Confirmed", 
    cadre: "Accountant", 
    department: "Finance",
    ministry: "Finance and Planning",
    institution: "Treasury Office",
    appointmentType: "Permanent",
    contractType: "Full-time",
    recentTitleDate: "2019-03-15",
    currentReportingOffice: "Chief Accountant",
    currentWorkplace: "Treasury Building",
    employmentDate: "2018-09-15",
    confirmationDate: "2019-03-15",
    ardhilHaliUrl: "https://placehold.co/ardhil-hali-fatma.pdf",
    confirmationLetterUrl: "https://placehold.co/confirmation-fatma.pdf",
    certificates: [
      { type: "Diploma", name: "Diploma in Accountancy", url: "https://placehold.co/diploma-fatma.pdf" },
    ],
  },
  { 
    id: "emp4", 
    employeeEntityId: "emp4_id", 
    name: "Hassan Mzee Juma", 
    zanId: "445678912", 
    zssfNumber: "ZSSF004",
    payrollNumber: "PAY004",
    dateOfBirth: "1975-09-01",
    placeOfBirth: "Unguja Ukuu",
    region: "Kusini Unguja",
    countryOfBirth: "Tanzania",
    status: "Confirmed", 
    cadre: "IT Support", 
    department: "ICT",
    ministry: "Information, Communication and Information Technology",
    institution: "e-Government Agency",
    appointmentType: "Permanent",
    contractType: "Full-time",
    recentTitleDate: "2017-07-20",
    currentReportingOffice: "Head of ICT",
    currentWorkplace: "Tech Park",
    employmentDate: "2017-01-20",
    confirmationDate: "2017-07-20",
    certificates: [], // No certificates listed for this employee
  },
  { 
    id: "emp5", 
    employeeEntityId: "emp5_id", 
    name: "Zainab Ali Khamis", 
    zanId: "556789345", 
    zssfNumber: "ZSSF005",
    payrollNumber: "PAY005",
    dateOfBirth: "1992-12-30",
    placeOfBirth: "Mkoani, Pemba",
    region: "Kusini Pemba",
    countryOfBirth: "Tanzania",
    status: "Confirmed", 
    cadre: "Planning Officer", 
    department: "Planning",
    ministry: "Finance and Planning",
    institution: "Planning Commission",
    appointmentType: "Permanent",
    contractType: "Full-time",
    recentTitleDate: "2022-08-01",
    currentReportingOffice: "Director of Planning",
    currentWorkplace: "Planning HQ",
    employmentDate: "2022-02-01",
    confirmationDate: "2022-08-01",
  },
  { 
    id: "emp6", 
    employeeEntityId: "emp6_id", 
    name: "Juma Omar Ali", 
    zanId: "667890456", 
    zssfNumber: "ZSSF006",
    payrollNumber: "PAY006",
    dateOfBirth: "1983-06-18",
    placeOfBirth: "Zanzibar City",
    region: "Mjini Magharibi",
    countryOfBirth: "Tanzania",
    status: "Confirmed", 
    cadre: "Procurement Officer", 
    department: "Procurement",
    ministry: "Finance and Planning",
    institution: "Government Procurement Services Agency",
    appointmentType: "Permanent",
    contractType: "Full-time",
    recentTitleDate: "2016-04-11",
    currentReportingOffice: "Head of Procurement",
    currentWorkplace: "GPSA Office",
    employmentDate: "2015-10-11",
    confirmationDate: "2016-04-11",
  },
  { 
    id: "emp7", 
    employeeEntityId: "emp7_id", 
    name: "Hamid Khalfan Abdalla", 
    zanId: "778901234", 
    zssfNumber: "ZSSF007",
    payrollNumber: "PAY007",
    dateOfBirth: "1978-03-25",
    placeOfBirth: "Stone Town",
    region: "Mjini Magharibi",
    countryOfBirth: "Tanzania",
    status: "Confirmed", 
    cadre: "Senior Driver", 
    department: "Transport",
    ministry: "Works and Transport",
    institution: "Government Garage",
    appointmentType: "Permanent",
    contractType: "Full-time",
    recentTitleDate: "2015-01-01",
    currentReportingOffice: "Transport Officer",
    currentWorkplace: "Central Garage",
    employmentDate: "2010-01-01",
    confirmationDate: "2010-07-01",
    ardhilHaliUrl: "https://placehold.co/ardhil-hali-hamid.pdf",
    confirmationLetterUrl: "https://placehold.co/confirmation-hamid.pdf",
  },
];

export const APP_NAME = "Civil Service Navigator";
